/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spdvi;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Alumne
 */
public class MainFormIMG extends javax.swing.JFrame {

    /**
     * Creates new form MainFormIMG
     */
    public MainFormIMG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage1 = new javax.swing.JLabel();
        lblImage2 = new javax.swing.JLabel();
        btnResizeImage = new javax.swing.JButton();
        btnImage2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spdvi/images/pexels-photo-206434.jpeg"))); // NOI18N

        lblImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spdvi/images/pexels-photo-878846.jpeg"))); // NOI18N

        btnResizeImage.setText("Resize 1");
        btnResizeImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResizeImageActionPerformed(evt);
            }
        });

        btnImage2.setText("Resize 2");
        btnImage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImage2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnResizeImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImage2)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResizeImage)
                    .addComponent(btnImage2))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResizeImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResizeImageActionPerformed
        BufferedImage originalImage = null;
        try{
            originalImage = originalImage = ImageIO.read(new File("src/spdvi/images/pexels-photo-206434.jpeg"));
            ImageIcon icon = resizeImageIcon(originalImage, lblImage1);
            lblImage1.setIcon(icon);
        } 
        catch(IOException ioe){
            ioe.printStackTrace(); 
        }
    }//GEN-LAST:event_btnResizeImageActionPerformed

    private void btnImage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImage2ActionPerformed
        BufferedImage originalImage = null;
        try{
            originalImage = originalImage = ImageIO.read(new File("src/spdvi/images/pexels-photo-878846.jpeg"));
            ImageIcon icon = resizeImageIcon(originalImage, lblImage2);
            lblImage2.setIcon(icon);
        } 
        catch(IOException ioe){
            ioe.printStackTrace(); 
        }
    }//GEN-LAST:event_btnImage2ActionPerformed

    private ImageIcon resizeImageIcon(BufferedImage originalImage, JLabel label){
        float aspectRatio = (float) originalImage.getWidth() / (float) originalImage.getHeight();
        int desiredWidth;
        int desiredHeight;
        
        if(label.getWidth() > label.getHeight()) {
            desiredWidth = Math.round(label.getHeight() * aspectRatio);
            desiredHeight = label.getHeight();
        }
        else {
            desiredHeight = Math.round(label.getWidth() / aspectRatio);
            desiredWidth = label.getWidth();
        }
            
            Image resultingImage = originalImage.getScaledInstance(desiredWidth, desiredHeight, Image.SCALE_SMOOTH);
            BufferedImage outputImage = new BufferedImage(desiredWidth, desiredHeight, BufferedImage.TYPE_INT_RGB);
            outputImage.getGraphics().drawImage(resultingImage, 0, 0, null);
            ImageIcon icon = new ImageIcon(outputImage);

            return icon;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormIMG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormIMG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormIMG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormIMG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormIMG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage2;
    private javax.swing.JButton btnResizeImage;
    private javax.swing.JLabel lblImage1;
    private javax.swing.JLabel lblImage2;
    // End of variables declaration//GEN-END:variables
}
